#!/usr/bin/python

import socket
import sys
from sense_hat import SenseHat

sense = SenseHat()

UDP_IP = sys.argv[1]
UDP_PORT = int(sys.argv[2])

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))

print("start sense_hat udp server on %s:%s\n" % (UDP_IP, UDP_PORT));

# commands are:
# quit : kills the server
# clear : clears all pixels
# pixel 1,2,3,4,5 : # sets pixel (1,2) to [r, g, b] value [3, 4, 5]

while True:
    data, addr = sock.recvfrom(128) # don't need a large buffer
    if data == "clear\n":
        sense.clear(0, 0, 0)
    elif data == "quit\n": 
        sense.clear(0, 0, 0)
        print("quitting sense_hat server...")
        quit()
    elif data.startswith("pixel "):
        outer_parts = data.split(" ")
        parts = outer_parts[1].split(",")
        x = int(parts[0])
        y = int(parts[1])
        r = int(parts[2])
        g = int(parts[3])
        b = int(parts[4])
        print("(%d, %d) [%d %d %d]" % (x, y, r, g, b))
        sense.set_pixel(x, y, r, g, b)
